version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - HOST=0.0.0.0
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/hospital
      - APP_SECRET=yourSuperSecret
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app  # Bind mount local code for live updates
      - /usr/src/app/node_modules  # Ensure node_modules are handled by container
    command: nodemon app.js  # Run nodemon to watch for changes

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
